### ISSUE TITLE
Working with child themes and using grunt

### ISSUE THREAD

**Issue by netzaffin** [OXID-eSales/flow_theme#43]
Hello,

I'm working on my first oxid project and need an advice for the setup with grunt.
i have the "flow" folder, a copy "projectname" folder and an (empty) "projectname-child" folder for changes.

I would copy the complete grunt setup to the "...-child" folder since all changes are stored there. Is this how it used to be?

Kind regards,
Patrick

**Comment by floeschie** [comment]
Hi, I would suggest to use our [forum](http://forum.oxid-esales.com/forumdisplay.php?f=9) and/or the [mailing list](http://lists.oxidforge.org/mailman/listinfo/dev-general) or the [community channel on Skype] for your request, as this is an issue tracker, not a community support channel. You will most likely get a quick answer there. 

Thanks!
